import { repositories, appState } from '../state.js';
import { openModal } from '../components/modal.js';
import { confirmDialog } from '../components/confirm-dialog.js';
import { showToast } from '../components/toast.js';
import { formatCurrency } from '../utils/formatting.js';
import { monthKey, toDateKey } from '../utils/dates.js';
import { summarizeExpenses } from '../services/expense-service.js';
import { bindAction, consumeHashAction, e, emptyState, field, handleError, numberValue, textArea, value } from './view-helpers.js';

let selectedMonth=monthKey();
function expenseForm(record={}){return `<div class="form-grid">${field('amount','Bedrag',record,{type:'number',required:true,min:'0.01',step:'0.01'})}${field('date','Datum',{date:record.date||toDateKey()},{type:'date',required:true})}${field('category','Categorie',{category:record.category||'Boodschappen'},{options:appState.settings.categories.expenses})}${field('description','Omschrijving',record,{required:true})}${field('paymentMethod','Betaalmethode',{paymentMethod:record.paymentMethod||'Pinpas'},{options:['Pinpas','Contant','Creditcard','Overboeking','Overig']})}${field('paidBy','Betaald door',{paidBy:record.paidBy||appState.settings.members[0]?.id},{options:appState.settings.members.map(m=>({value:m.id,label:m.name}))})}${textArea('note','Notitie',record,'full')}</div>`}
function openExpense(record=null){const editing=Boolean(record);openModal({title:editing?'Uitgave aanpassen':'Uitgave toevoegen',content:expenseForm(record||{}),submitLabel:'Opslaan',onSubmit:async data=>{const expense={amount:numberValue(data,'amount'),date:value(data,'date'),category:value(data,'category'),description:value(data,'description'),paymentMethod:value(data,'paymentMethod'),paidBy:value(data,'paidBy'),note:value(data,'note')};if(expense.amount<=0)throw new Error('Vul een bedrag hoger dan nul in.');if(!expense.description)throw new Error('Vul een omschrijving in.');if(editing)await repositories.expenses.update(record.id,expense);else await repositories.expenses.create(expense);showToast('Uitgave opgeslagen.');await refreshExpenses()}})}
async function refreshExpenses(){const root=document.querySelector('#expense-list');if(!root)return;const all=await repositories.expenses.getAll();const items=all.filter(item=>item.date?.startsWith(selectedMonth)).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));const summary=summarizeExpenses(items);const total=summary.total;document.querySelector('#expense-total').textContent=formatCurrency(total,appState.settings.currency);const categoryTotals=Object.entries(summary.byCategory).sort((a,b)=>b[1]-a[1]);const memberTotals=appState.settings.members.map(member=>({member,total:summary.byMember[member.id]||0})).filter(entry=>entry.total>0);document.querySelector('#expense-breakdown').innerHTML=categoryTotals.length?categoryTotals.map(([category,amount])=>`<div><div class="card-header"><span>${e(category)}</span><strong>${formatCurrency(amount,appState.settings.currency)}</strong></div><div class="progress"><span style="width:${total?Math.round(amount/total*100):0}%"></span></div><p class="small muted">${total?Math.round(amount/total*100):0}% van deze maand</p></div>`).join(''):emptyState('Nog geen verdeling','Voeg een uitgave toe voor het categorieoverzicht.');document.querySelector('#expense-members').innerHTML=memberTotals.length?memberTotals.map(({member,total:amount})=>`<div class="list-item"><span class="member-dot" style="--member-color:${member.color}"></span><div class="list-item-main"><strong>${e(member.name)}</strong></div><strong>${formatCurrency(amount,appState.settings.currency)}</strong></div>`).join(''):'<p class="muted">Nog geen uitgaven per gezinslid.</p>';
root.innerHTML=items.length?`<ul class="item-list">${items.map(item=>{const member=appState.settings.members.find(m=>m.id===item.paidBy);return `<li class="list-item"><div class="list-item-main"><h3 class="list-item-title">${e(item.description)}</h3><div class="list-item-meta"><span>${e(item.date)}</span><span>${e(item.category)}</span>${member?`<span>Door ${e(member.name)}</span>`:''}</div></div><strong>${formatCurrency(item.amount,appState.settings.currency)}</strong><div class="list-actions"><button class="mini-action" data-edit-expense="${item.id}" aria-label="Aanpassen">✎</button><button class="mini-action danger" data-delete-expense="${item.id}" aria-label="Verwijderen">⌫</button></div></li>`}).join('')}</ul>`:emptyState('Nog geen uitgaven','Deze maand zijn nog geen uitgaven ingevoerd.','<button class="button" data-add-expense>＋ Uitgave toevoegen</button>')}
export const expensesView={async render(){return `<section class="page-stack"><div class="page-header"><div><span class="metric-label">Totaal geselecteerde maand</span><strong class="metric" id="expense-total">€ 0,00</strong></div><button class="button" data-add-expense>＋ Uitgave</button></div><div class="toolbar">${field('expense-month','Maand',{ 'expense-month':selectedMonth},{type:'month'})}</div><div class="content-grid two"><section class="card"><h2>Per categorie</h2><div id="expense-breakdown" class="page-stack"></div></section><section class="card"><h2>Per gezinslid</h2><div id="expense-members" class="item-list"></div></section></div><section><h2>Recente uitgaven</h2><div id="expense-list"></div></section></section>`},async mount(root){bindAction(root,'[data-add-expense]',()=>openExpense());root.querySelector('[name="expense-month"]').addEventListener('change',async event=>{selectedMonth=event.target.value;await refreshExpenses()});bindAction(root,'[data-edit-expense]',async button=>{const item=await repositories.expenses.getById(button.dataset.editExpense);if(item)openExpense(item)});bindAction(root,'[data-delete-expense]',async button=>{const item=await repositories.expenses.getById(button.dataset.deleteExpense);if(item&&await confirmDialog({message:`De uitgave “${e(item.description)}” wordt verwijderd.`})){await repositories.expenses.softDelete(item.id);showToast('Uitgave verwijderd.');await refreshExpenses()}});await refreshExpenses().catch(handleError);if(consumeHashAction('1'))openExpense()}};
