import { repositories } from '../state.js';
import { openModal } from '../components/modal.js';
import { confirmDialog } from '../components/confirm-dialog.js';
import { showToast } from '../components/toast.js';
import { toDateKey } from '../utils/dates.js';
import { getInventoryWarning } from '../services/inventory-service.js';
import { bindAction, e, emptyState, field, handleError, numberValue, textArea, value } from './view-helpers.js';

let inventoryFilter='';
function inventoryForm(record={}){return `<div class="form-grid">${field('productName','Productnaam',record,{required:true,className:'full'})}${field('category','Categorie',{category:record.category||'Overig'},{options:['Groente en fruit','Zuivel','Voorraadkast','Diepvries','Drinken','Huishouden','Huisdieren','Overig']})}${field('storageLocation','Opslaglocatie',record,{placeholder:'Koelkast, vriezer…'})}${field('quantity','Hoeveelheid',record,{type:'number',min:'0',step:'0.01'})}${field('unit','Eenheid',record,{options:['stuks','pak','gram','kilogram','liter','milliliter','doos']})}${field('minimumQuantity','Minimumhoeveelheid',record,{type:'number',min:'0',step:'0.01'})}${field('expiryDate','Houdbaarheidsdatum',record,{type:'date'})}${textArea('notes','Notities',record,'full')}</div>`}
function openInventory(record=null){const editing=Boolean(record);openModal({title:editing?'Voorraad aanpassen':'Product aan voorraad toevoegen',content:inventoryForm(record||{quantity:1,minimumQuantity:1}),submitLabel:'Opslaan',onSubmit:async data=>{const item={productName:value(data,'productName'),category:value(data,'category'),storageLocation:value(data,'storageLocation'),quantity:numberValue(data,'quantity'),unit:value(data,'unit'),minimumQuantity:numberValue(data,'minimumQuantity'),expiryDate:value(data,'expiryDate')||null,notes:value(data,'notes')};if(!item.productName)throw new Error('Vul een productnaam in.');if(editing)await repositories.inventory.update(record.id,item);else await repositories.inventory.create(item);showToast('Voorraad opgeslagen.');await refreshInventory()}})}
async function refreshInventory(){const root=document.querySelector('#inventory-list');if(!root)return;let items=await repositories.inventory.getAll();const query=inventoryFilter.toLocaleLowerCase('nl-NL');items=items.filter(item=>!query||[item.productName,item.category,item.storageLocation].join(' ').toLocaleLowerCase('nl-NL').includes(query)).sort((a,b)=>getInventoryWarning(b).messages.length-getInventoryWarning(a).messages.length||a.productName.localeCompare(b.productName,'nl'));const alerts=items.filter(item=>getInventoryWarning(item).messages.length);document.querySelector('#inventory-alert-count').textContent=`${alerts.length} waarschuwing${alerts.length===1?'':'en'}`;root.innerHTML=items.length?`<ul class="item-list">${items.map(item=>{const alert=getInventoryWarning(item);return `<li class="list-item"><div class="list-item-main"><h3 class="list-item-title">${e(item.productName)}</h3><div class="list-item-meta"><span>${e(item.quantity)} ${e(item.unit)}</span><span>${e(item.category)}</span>${item.storageLocation?`<span>${e(item.storageLocation)}</span>`:''}${alert.messages.map(message=>`<span class="badge ${alert.severity}">${e(message)}</span>`).join('')}</div></div><div class="list-actions"><button class="mini-action" data-inventory-shop="${item.id}" aria-label="Naar boodschappen">▤</button><button class="mini-action" data-edit-inventory="${item.id}" aria-label="Aanpassen">✎</button><button class="mini-action danger" data-delete-inventory="${item.id}" aria-label="Verwijderen">⌫</button></div></li>`}).join('')}</ul>`:emptyState('Nog geen voorraad','Voeg producten toe om tekorten en houdbaarheid bij te houden.','<button class="button" data-add-inventory>＋ Product toevoegen</button>')}
export const inventoryView={async render(){return `<section class="page-stack"><div class="page-header"><p class="muted" id="inventory-alert-count">0 waarschuwingen</p><button class="button" data-add-inventory>＋ Voorraad</button></div><div class="toolbar"><div class="field grow"><label for="inventory-search">Zoeken</label><input id="inventory-search" type="search" placeholder="Product, categorie of plek"></div></div><div id="inventory-list"></div></section>`},async mount(root){bindAction(root,'[data-add-inventory]',()=>openInventory());root.querySelector('#inventory-search').addEventListener('input',async event=>{inventoryFilter=event.target.value;await refreshInventory()});bindAction(root,'[data-edit-inventory]',async button=>{const item=await repositories.inventory.getById(button.dataset.editInventory);if(item)openInventory(item)});bindAction(root,'[data-inventory-shop]',async button=>{const item=await repositories.inventory.getById(button.dataset.inventoryShop);if(!item)return;await repositories.shopping.create({productName:item.productName,quantity:Math.max(1,Number(item.minimumQuantity)-Number(item.quantity)+1),unit:item.unit,category:item.category,store:'',note:'Vanuit voorraad',addedBy:'device',checked:false,checkedAt:null,checkedBy:null});showToast('Toegevoegd aan boodschappen.')});bindAction(root,'[data-delete-inventory]',async button=>{const item=await repositories.inventory.getById(button.dataset.deleteInventory);if(item&&await confirmDialog({message:`“${e(item.productName)}” wordt verwijderd.`})){await repositories.inventory.softDelete(item.id);showToast('Voorraadproduct verwijderd.');await refreshInventory()}});await refreshInventory().catch(handleError)}};
