import { repositories } from '../state.js';
import { openModal } from '../components/modal.js';
import { confirmDialog } from '../components/confirm-dialog.js';
import { showToast } from '../components/toast.js';
import { addDays, dateRange, formatDate, fromDateKey, startOfWeek, toDateKey } from '../utils/dates.js';
import { addMealIngredientsToShopping } from '../services/meal-service.js';
import { bindAction, boolValue, consumeHashAction, e, emptyState, field, handleError, textArea, value } from './view-helpers.js';

let weekCursor = startOfWeek(new Date());
const mealTypes = [['breakfast','Ontbijt'],['lunch','Lunch'],['dinner','Avondeten'],['snack','Tussendoortje']];

function mealForm(record={}){return `<div class="form-grid">${field('name','Maaltijd',record,{required:true,className:'full',placeholder:'Wat eten jullie?'})}${field('date','Dag',{date:record.date||toDateKey()},{type:'date',required:true})}${field('mealType','Moment',{mealType:record.mealType||'dinner'},{options:mealTypes.map(([value,label])=>({value,label}))})}${textArea('ingredients','Ingrediënten (één per regel)',record,'full')}${textArea('notes','Notities',record,'full')}<div class="full"><label class="check-row"><input type="checkbox" name="favorite" ${record.favorite?'checked':''}> Bewaren als favoriet</label></div></div>`}

function openMeal(record=null, defaults={}){const editing=Boolean(record);openModal({title:editing?'Maaltijd aanpassen':'Maaltijd toevoegen',content:mealForm(record||defaults),submitLabel:editing?'Opslaan':'Toevoegen',onSubmit:async(data)=>{const meal={kind:'plan',name:value(data,'name'),date:value(data,'date'),mealType:value(data,'mealType'),ingredients:value(data,'ingredients'),notes:value(data,'notes'),favorite:boolValue(data,'favorite')};if(!meal.name)throw new Error('Vul een maaltijd in.');if(editing)await repositories.meals.update(record.id,meal);else await repositories.meals.create(meal);showToast(editing?'Maaltijd aangepast.':'Maaltijd toegevoegd.');await refreshMeals()}})}

function recipeForm(record={}){return `<div class="form-grid">${field('name','Naam recept',record,{required:true,className:'full'})}${textArea('ingredients','Ingrediënten (één per regel)',record,'full')}${textArea('instructions','Bereiding',record,'full')}<div class="full"><label class="check-row"><input type="checkbox" name="favorite" ${record.favorite?'checked':''}> Favoriet recept</label></div></div>`}
function openRecipe(record=null){const editing=Boolean(record);openModal({title:editing?'Recept aanpassen':'Recept opslaan',content:recipeForm(record||{}),submitLabel:'Opslaan',onSubmit:async(data)=>{const recipe={kind:'recipe',name:value(data,'name'),ingredients:value(data,'ingredients'),instructions:value(data,'instructions'),favorite:boolValue(data,'favorite')};if(!recipe.name)throw new Error('Vul een naam in.');if(editing)await repositories.meals.update(record.id,recipe);else await repositories.meals.create(recipe);showToast('Recept opgeslagen.');await refreshMeals()}})}

async function ingredientsToShopping(item){const count=await addMealIngredientsToShopping(item,repositories.shopping);if(!count){showToast('Deze maaltijd heeft nog geen ingrediënten.','error');return}showToast(`${count} ingrediënten toegevoegd aan boodschappen.`)}

function openCopyMeal(item){openModal({title:'Maaltijd kopiëren',content:`<div class="form-grid">${field('date','Kopiëren naar',{date:toDateKey(addDays(fromDateKey(item.date),1))},{type:'date',required:true})}${field('mealType','Moment',{mealType:item.mealType},{options:mealTypes.map(([value,label])=>({value,label}))})}</div>`,submitLabel:'Kopiëren',onSubmit:async(data)=>{const {id,createdAt,updatedAt,deletedAt,version,deviceId,syncStatus,updatedBy,...copy}=item;await repositories.meals.create({...copy,date:value(data,'date'),mealType:value(data,'mealType')});showToast('Maaltijd gekopieerd.');await refreshMeals()}})}

async function refreshMeals(){const planner=document.querySelector('#meal-week');const recipesRoot=document.querySelector('#recipe-list');if(!planner)return;const all=await repositories.meals.getAll();const plans=all.filter(item=>item.kind==='plan');const recipes=all.filter(item=>item.kind==='recipe');const days=dateRange(weekCursor,addDays(weekCursor,6));document.querySelector('#meal-week-label').textContent=`${formatDate(days[0],{day:'numeric',month:'short'})} – ${formatDate(days[6],{day:'numeric',month:'short',year:'numeric'})}`;
planner.innerHTML=days.map(day=>{const key=toDateKey(day);const dayMeals=plans.filter(item=>item.date===key);return `<section class="card compact"><div class="card-header"><div><span class="small muted">${formatDate(day,{weekday:'long'})}</span><h3>${formatDate(day,{day:'numeric',month:'long'})}</h3></div><button class="mini-action" data-add-meal="${key}" aria-label="Maaltijd toevoegen">＋</button></div><div class="item-list">${mealTypes.map(([type,label])=>{const item=dayMeals.find(meal=>meal.mealType===type);return item?`<div class="list-item compact"><div class="list-item-main"><span class="small muted">${label}</span><div class="list-item-title">${e(item.name)} ${item.favorite?'♥':''}</div></div><div class="list-actions"><button class="mini-action" data-shop-meal="${item.id}" aria-label="Ingrediënten naar boodschappen">▤</button><button class="mini-action" data-copy-meal="${item.id}" aria-label="Kopiëren">⧉</button><button class="mini-action" data-edit-meal="${item.id}" aria-label="Aanpassen">✎</button><button class="mini-action danger" data-delete-meal="${item.id}" aria-label="Verwijderen">⌫</button></div></div>`:`<button class="button ghost small" data-add-meal="${key}" data-meal-type="${type}">＋ ${label}</button>`}).join('')}</div>${dayMeals.find(m=>m.notes)?`<p class="small muted">${e(dayMeals.find(m=>m.notes).notes)}</p>`:''}</section>`}).join('');
recipesRoot.innerHTML=recipes.length?`<ul class="item-list">${recipes.sort((a,b)=>Number(b.favorite)-Number(a.favorite)).map(item=>`<li class="list-item"><div class="list-item-main"><h3 class="list-item-title">${item.favorite?'♥ ':''}${e(item.name)}</h3><div class="list-item-meta"><span>${String(item.ingredients||'').split(/\r?\n/).filter(Boolean).length} ingrediënten</span></div></div><div class="list-actions"><button class="mini-action" data-shop-meal="${item.id}" aria-label="Ingrediënten naar boodschappen">▤</button><button class="mini-action" data-edit-recipe="${item.id}" aria-label="Aanpassen">✎</button><button class="mini-action danger" data-delete-meal="${item.id}" aria-label="Verwijderen">⌫</button></div></li>`).join('')}</ul>`:emptyState('Nog geen recepten','Sla een favoriet recept op om het snel terug te vinden.')}

export const mealsView={async render(){return `<section class="page-stack"><div class="page-header"><div class="calendar-nav"><button class="icon-button" id="meal-prev" aria-label="Vorige week">‹</button><h2 id="meal-week-label"></h2><button class="icon-button" id="meal-next" aria-label="Volgende week">›</button></div><button class="button" data-add-meal="${toDateKey()}">＋ Maaltijd</button></div><div id="meal-week" class="content-grid three"></div><div class="page-header"><h2>Recepten en favorieten</h2><button class="button secondary" id="add-recipe">＋ Recept</button></div><div id="recipe-list"></div></section>`},async mount(root){root.querySelector('#meal-prev').addEventListener('click',async()=>{weekCursor=addDays(weekCursor,-7);await refreshMeals()});root.querySelector('#meal-next').addEventListener('click',async()=>{weekCursor=addDays(weekCursor,7);await refreshMeals()});root.querySelector('#add-recipe').addEventListener('click',()=>openRecipe());bindAction(root,'[data-add-meal]',button=>openMeal(null,{date:button.dataset.addMeal,mealType:button.dataset.mealType||'dinner'}));bindAction(root,'[data-edit-meal]',async button=>{const item=await repositories.meals.getById(button.dataset.editMeal);if(item)openMeal(item)});bindAction(root,'[data-edit-recipe]',async button=>{const item=await repositories.meals.getById(button.dataset.editRecipe);if(item)openRecipe(item)});bindAction(root,'[data-copy-meal]',async button=>{const item=await repositories.meals.getById(button.dataset.copyMeal);if(item)openCopyMeal(item)});bindAction(root,'[data-shop-meal]',async button=>{const item=await repositories.meals.getById(button.dataset.shopMeal);if(item)await ingredientsToShopping(item)});bindAction(root,'[data-delete-meal]',async button=>{const item=await repositories.meals.getById(button.dataset.deleteMeal);if(item&&await confirmDialog({message:`“${e(item.name)}” wordt verwijderd.`})){await repositories.meals.softDelete(item.id);showToast('Verwijderd.');await refreshMeals()}});await refreshMeals().catch(handleError);if(consumeHashAction('1'))openMeal(null,{date:toDateKey(),mealType:'dinner'})}};
