import { repositories, appState } from '../state.js';
import { openModal } from '../components/modal.js';
import { confirmDialog } from '../components/confirm-dialog.js';
import { showToast } from '../components/toast.js';
import { formatCurrency } from '../utils/formatting.js';
import { safeUrl } from '../utils/sanitization.js';
import { bindAction, boolValue, e, emptyState, field, handleError, numberValue, textArea, value } from './view-helpers.js';

let outingFilter='all';
function outingForm(record={}){return `<div class="form-grid">${field('name','Naam',record,{required:true,className:'full'})}${field('location','Locatie',record)}${field('date','Datum',record,{type:'date'})}${field('estimatedPrice','Geschatte prijs',record,{type:'number',min:'0',step:'0.01'})}${field('website','Website',record,{type:'url',className:'full',placeholder:'https://…'})}${field('travelTime','Reistijd',record,{placeholder:'Bijvoorbeeld: 45 minuten'})}${field('category','Categorie',{category:record.category||'Overig'},{options:appState.settings.categories.outings})}${textArea('notes','Notities',record,'full')}<div class="full check-grid"><label><input type="checkbox" name="favorite" ${record.favorite?'checked':''}> Favoriet</label><label><input type="checkbox" name="planned" ${record.planned?'checked':''}> Gepland</label><label><input type="checkbox" name="completed" ${record.completed?'checked':''}> Afgerond</label></div></div>`}
function openOuting(record=null){const editing=Boolean(record);openModal({title:editing?'Uitje aanpassen':'Uitje of idee toevoegen',content:outingForm(record||{}),submitLabel:'Opslaan',onSubmit:async data=>{const outing={name:value(data,'name'),location:value(data,'location'),date:value(data,'date')||null,estimatedPrice:numberValue(data,'estimatedPrice'),website:value(data,'website'),travelTime:value(data,'travelTime'),category:value(data,'category'),notes:value(data,'notes'),favorite:boolValue(data,'favorite'),planned:boolValue(data,'planned'),completed:boolValue(data,'completed')};if(!outing.name)throw new Error('Vul een naam in.');if(outing.website&&!safeUrl(outing.website))throw new Error('Vul een geldige website in die begint met http:// of https://.');if(editing)await repositories.outings.update(record.id,outing);else await repositories.outings.create(outing);showToast('Uitje opgeslagen.');await refreshOutings()}})}
async function refreshOutings(){const root=document.querySelector('#outing-list');if(!root)return;let items=await repositories.outings.getAll();items=items.filter(item=>outingFilter==='all'||(outingFilter==='favorites'?item.favorite:outingFilter==='planned'?item.planned&&!item.completed:outingFilter==='completed'?item.completed:true)).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||String(a.date||'9999').localeCompare(String(b.date||'9999')));root.innerHTML=items.length?`<div class="content-grid three">${items.map(item=>`<article class="card ${item.completed?'is-complete':''}"><div class="card-header"><div><span class="badge">${e(item.category)}</span><h2>${item.favorite?'♥ ':''}${e(item.name)}</h2></div><div class="list-actions"><button class="mini-action" data-edit-outing="${item.id}" aria-label="Aanpassen">✎</button><button class="mini-action danger" data-delete-outing="${item.id}" aria-label="Verwijderen">⌫</button></div></div><div class="item-list"><div class="list-item-meta">${item.location?`<span>⌖ ${e(item.location)}</span>`:''}${item.date?`<span>${e(item.date)}</span>`:''}${item.travelTime?`<span>Reistijd ${e(item.travelTime)}</span>`:''}</div>${item.estimatedPrice?`<strong>${formatCurrency(item.estimatedPrice,appState.settings.currency)}</strong>`:''}${item.notes?`<p class="muted">${e(item.notes)}</p>`:''}${safeUrl(item.website)?`<a class="button secondary small" href="${e(safeUrl(item.website))}" target="_blank" rel="noopener noreferrer">Website openen</a>`:''}<button class="button ghost small" data-toggle-outing="${item.id}">${item.completed?'Opnieuw openen':'Markeer als afgerond'}</button></div></article>`).join('')}</div>`:emptyState('Geen uitjes in dit overzicht','Bewaar een idee, dagje weg of vakantie.','<button class="button" data-add-outing>＋ Idee toevoegen</button>')}
export const outingsView={async render(){return `<section class="page-stack"><div class="page-header"><p class="muted">Ideeën, dagjes weg en vakanties.</p><button class="button" data-add-outing>＋ Uitje</button></div><div class="segmented"><button class="active" data-outing-filter="all">Alles</button><button data-outing-filter="favorites">Favorieten</button><button data-outing-filter="planned">Gepland</button><button data-outing-filter="completed">Afgerond</button></div><div id="outing-list"></div></section>`},async mount(root){bindAction(root,'[data-add-outing]',()=>openOuting());root.querySelectorAll('[data-outing-filter]').forEach(button=>button.addEventListener('click',async()=>{outingFilter=button.dataset.outingFilter;root.querySelectorAll('[data-outing-filter]').forEach(b=>b.classList.toggle('active',b===button));await refreshOutings()}));bindAction(root,'[data-edit-outing]',async button=>{const item=await repositories.outings.getById(button.dataset.editOuting);if(item)openOuting(item)});bindAction(root,'[data-toggle-outing]',async button=>{const item=await repositories.outings.getById(button.dataset.toggleOuting);await repositories.outings.update(item.id,{completed:!item.completed});showToast(item.completed?'Uitje heropend.':'Uitje afgerond.');await refreshOutings()});bindAction(root,'[data-delete-outing]',async button=>{const item=await repositories.outings.getById(button.dataset.deleteOuting);if(item&&await confirmDialog({message:`“${e(item.name)}” wordt verwijderd.`})){await repositories.outings.softDelete(item.id);showToast('Uitje verwijderd.');await refreshOutings()}});await refreshOutings().catch(handleError)}};
