import { repositories } from '../state.js';
import { openModal } from '../components/modal.js';
import { confirmDialog } from '../components/confirm-dialog.js';
import { showToast } from '../components/toast.js';
import { formatDate, toDateKey } from '../utils/dates.js';
import { bindAction, e, emptyState, field, handleError, textArea, value } from './view-helpers.js';

function petForm(record={}){return `<div class="form-grid">${field('name','Naam',record,{required:true})}${field('species','Diersoort',record,{required:true,placeholder:'Hond, kat…'})}${field('breed','Ras',record)}${field('birthDate','Geboortedatum',record,{type:'date'})}${field('vet','Dierenarts',record)}${field('weight','Gewicht',record,{type:'number',min:'0',step:'0.1'})}${field('medication','Medicatie',record)}${field('dosage','Dosering',record)}${field('medicationTime','Medicatietijd',record,{type:'time'})}${field('vetAppointment','Volgende dierenartsafspraak',record,{type:'datetime-local'})}${textArea('appointments','Afspraken en historie',record,'full')}${textArea('vaccinations','Vaccinaties',record,'full')}${textArea('notes','Notities',record,'full')}</div>`}
function openPet(record=null){const editing=Boolean(record);openModal({title:editing?'Huisdier aanpassen':'Huisdier toevoegen',content:petForm(record||{}),submitLabel:'Opslaan',wide:true,onSubmit:async data=>{const pet={name:value(data,'name'),species:value(data,'species'),breed:value(data,'breed'),birthDate:value(data,'birthDate')||null,vet:value(data,'vet'),weight:value(data,'weight'),medication:value(data,'medication'),dosage:value(data,'dosage'),medicationTime:value(data,'medicationTime'),vetAppointment:value(data,'vetAppointment')||null,appointments:value(data,'appointments'),vaccinations:value(data,'vaccinations'),notes:value(data,'notes')};if(!pet.name||!pet.species)throw new Error('Vul de naam en diersoort in.');if(editing)await repositories.pets.update(record.id,pet);else await repositories.pets.create(pet);showToast('Huisdier opgeslagen.');await refreshPets()}})}
async function refreshPets(){const root=document.querySelector('#pet-list');if(!root)return;const pets=await repositories.pets.getAll();root.innerHTML=pets.length?`<div class="content-grid two">${pets.map(pet=>`<article class="card"><div class="card-header"><div><span class="badge">${e(pet.species)}</span><h2>${e(pet.name)}</h2><p class="muted">${e(pet.breed||'Ras niet ingevuld')}</p></div><div class="list-actions"><button class="mini-action" data-edit-pet="${pet.id}" aria-label="Aanpassen">✎</button><button class="mini-action danger" data-delete-pet="${pet.id}" aria-label="Verwijderen">⌫</button></div></div><div class="item-list">${pet.birthDate?`<div class="list-item"><div><span class="small muted">Geboren</span><strong>${formatDate(pet.birthDate,{day:'numeric',month:'long',year:'numeric'})}</strong></div></div>`:''}${pet.medication?`<div class="list-item"><div><span class="small muted">Medicatie ${e(pet.medicationTime||'')}</span><strong>${e(pet.medication)} · ${e(pet.dosage||'dosering niet ingevuld')}</strong></div></div>`:''}${pet.vetAppointment?`<div class="list-item"><div><span class="small muted">Dierenarts</span><strong>${e(new Date(pet.vetAppointment).toLocaleString('nl-NL',{dateStyle:'medium',timeStyle:'short'}))}</strong></div></div>`:''}${pet.weight?`<div class="list-item"><div><span class="small muted">Gewicht</span><strong>${e(pet.weight)} kg</strong></div></div>`:''}</div></article>`).join('')}</div>`:emptyState('Nog geen huisdieren','Voeg een huisdier toe voor medicatie, vaccinaties en afspraken.','<button class="button" data-add-pet>＋ Huisdier toevoegen</button>')}
export const petsView={async render(){return `<section class="page-stack"><div class="page-header"><p class="muted">Verzorging, medicatie en dierenarts bij elkaar.</p><button class="button" data-add-pet>＋ Huisdier</button></div><div id="pet-list"></div></section>`},async mount(root){bindAction(root,'[data-add-pet]',()=>openPet());bindAction(root,'[data-edit-pet]',async button=>{const pet=await repositories.pets.getById(button.dataset.editPet);if(pet)openPet(pet)});bindAction(root,'[data-delete-pet]',async button=>{const pet=await repositories.pets.getById(button.dataset.deletePet);if(pet&&await confirmDialog({message:`Alle lokale gegevens van ${e(pet.name)} worden verwijderd.`})){await repositories.pets.softDelete(pet.id);showToast('Huisdier verwijderd.');await refreshPets()}});await refreshPets().catch(handleError)}};
