import { repositories, appState } from '../state.js';
import { openModal } from '../components/modal.js';
import { confirmDialog } from '../components/confirm-dialog.js';
import { showToast } from '../components/toast.js';
import { nextTaskDate } from '../services/recurrence-service.js';
import { toDateKey } from '../utils/dates.js';
import { bindAction, consumeHashAction, e, emptyState, field, handleError, numberValue, textArea, value } from './view-helpers.js';

let taskFilter='open';

function taskForm(record={}) { return `<div class="form-grid">${field('title','Titel',record,{required:true,className:'full'})}${textArea('description','Omschrijving',record,'full')}
  ${field('assignedTo','Toegewezen aan',{assignedTo:record.assignedTo||appState.settings.members[0]?.id},{options:appState.settings.members.map((m)=>({value:m.id,label:m.name}))})}
  ${field('priority','Prioriteit',{priority:record.priority||'normal'},{options:[{value:'low',label:'Laag'},{value:'normal',label:'Normaal'},{value:'high',label:'Hoog'},{value:'urgent',label:'Dringend'}]})}
  ${field('date','Einddatum',{date:record.date||toDateKey()},{type:'date'})}${field('time','Tijd',record,{type:'time'})}
  ${field('category','Categorie',{category:record.category||'Huishouden'},{options:['Huishouden','Kinderen','Tuin','Administratie','Huisdieren','Overig']})}
  ${field('recurrence','Herhaling',{recurrence:record.recurrence||'none'},{options:[{value:'none',label:'Niet herhalen'},{value:'daily',label:'Dagelijks'},{value:'weekly',label:'Wekelijks'},{value:'monthly',label:'Maandelijks'},{value:'custom',label:'Eigen interval'}]})}
  ${field('recurrenceInterval','Iedere', {recurrenceInterval:record.recurrenceInterval||1},{type:'number',min:'1'})}${field('recurrenceUnit','Intervaleenheid',{recurrenceUnit:record.recurrenceUnit||'days'},{options:[{value:'days',label:'dag(en)'},{value:'weeks',label:'week/weken'},{value:'months',label:'maand(en)'}]})}
  ${textArea('note','Notitie',record,'full')}</div>`; }

function openTask(record=null){const editing=Boolean(record);openModal({title:editing?'Taak aanpassen':'Nieuwe taak',content:taskForm(record||{}),submitLabel:editing?'Opslaan':'Taak toevoegen',onSubmit:async(data)=>{const task={title:value(data,'title'),description:value(data,'description'),assignedTo:value(data,'assignedTo'),priority:value(data,'priority'),date:value(data,'date'),time:value(data,'time'),category:value(data,'category'),recurrence:value(data,'recurrence'),recurrenceInterval:numberValue(data,'recurrenceInterval',1),recurrenceUnit:value(data,'recurrenceUnit'),status:editing?record.status:'open',note:value(data,'note'),parentTaskId:editing?record.parentTaskId||null:null};if(!task.title)throw new Error('Vul een titel in.');if(editing)await repositories.tasks.update(record.id,task);else await repositories.tasks.create(task);showToast(editing?'Taak aangepast.':'Taak toegevoegd.');await refreshTasks()}})}

async function completeTask(item){if(item.status==='done'){await repositories.tasks.update(item.id,{status:'open',completedAt:null});showToast('Taak heropend.');return}
  const completedAt=new Date();await repositories.tasks.update(item.id,{status:'done',completedAt:completedAt.toISOString()});const nextDate=nextTaskDate(item,completedAt);if(nextDate){const {id,createdAt,updatedAt,deletedAt,version,deviceId,syncStatus,updatedBy,completedAt:old,...copy}=item;await repositories.tasks.create({...copy,date:nextDate,status:'open',parentTaskId:item.parentTaskId||item.id});showToast(`Taak afgerond; de volgende staat op ${nextDate}.`)}else showToast('Taak afgerond.')}

async function refreshTasks(){const root=document.querySelector('#task-list');if(!root)return;let items=await repositories.tasks.getAll();items=items.filter((item)=>taskFilter==='all'||(taskFilter==='open'?item.status!=='done':item.status==='done')).sort((a,b)=>`${a.status==='done'}${a.date}${a.time}`.localeCompare(`${b.status==='done'}${b.date}${b.time}`));document.querySelector('#task-open-count').textContent=`${items.filter(i=>i.status!=='done').length} openstaand`;
root.innerHTML=items.length?`<ul class="item-list">${items.map((item)=>{const member=appState.settings.members.find(m=>m.id===item.assignedTo);return `<li class="list-item ${item.status==='done'?'is-complete':''}"><button class="mini-action" data-toggle-task="${item.id}" aria-label="${item.status==='done'?'Heropenen':'Afronden'}">${item.status==='done'?'↶':'✓'}</button><div class="list-item-main"><h3 class="list-item-title">${e(item.title)}</h3><div class="list-item-meta"><span class="badge ${e(item.priority)}">${({low:'Laag',normal:'Normaal',high:'Hoog',urgent:'Dringend'})[item.priority]}</span>${member?`<span style="color:${member.color}">● ${e(member.name)}</span>`:''}<span>${e(item.date||'Geen datum')} ${e(item.time||'')}</span>${item.recurrence!=='none'?'<span>↻ Herhalend</span>':''}</div></div><div class="list-actions"><button class="mini-action" data-edit-task="${item.id}" aria-label="Aanpassen">✎</button><button class="mini-action danger" data-delete-task="${item.id}" aria-label="Verwijderen">⌫</button></div></li>`}).join('')}</ul>`:emptyState('Geen taken hier','Alles is netjes bijgewerkt.','<button class="button" data-add-task>＋ Taak toevoegen</button>')}

export const tasksView={async render(){return `<section class="page-stack"><div class="page-header"><p class="muted" id="task-open-count">0 openstaand</p><button class="button" data-add-task>＋ Nieuwe taak</button></div><div class="segmented"><button data-task-filter="open" class="active">Openstaand</button><button data-task-filter="done">Afgerond</button><button data-task-filter="all">Alles</button></div><div id="task-list"></div></section>`},async mount(root){bindAction(root,'[data-add-task]',()=>openTask());root.querySelectorAll('[data-task-filter]').forEach(button=>button.addEventListener('click',async()=>{taskFilter=button.dataset.taskFilter;root.querySelectorAll('[data-task-filter]').forEach(b=>b.classList.toggle('active',b===button));await refreshTasks()}));bindAction(root,'[data-toggle-task]',async button=>{const item=await repositories.tasks.getById(button.dataset.toggleTask);await completeTask(item);await refreshTasks()});bindAction(root,'[data-edit-task]',async button=>{const item=await repositories.tasks.getById(button.dataset.editTask);if(item)openTask(item)});bindAction(root,'[data-delete-task]',async button=>{const item=await repositories.tasks.getById(button.dataset.deleteTask);if(item&&await confirmDialog({message:`“${e(item.title)}” wordt verwijderd.`})){await repositories.tasks.softDelete(item.id);showToast('Taak verwijderd.');await refreshTasks()}});await refreshTasks().catch(handleError);if(consumeHashAction('1'))openTask()}};
